# Generated by Django 3.1.4 on 2020-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20201230_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE'), ('PENDING', 'PENDING')], max_length=200, null=True),
        ),
    ]
